name: Deploy to Netlify

on:
  push:
    branches: [main]
    paths:
      - 'site/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Deploy to Netlify
        run: npx netlify-cli deploy --dir=site --prod --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
